### PR TITLE
RMHDR-200 Use yml config file instead of R script to store pipeline parameters

### PR DESCRIPTION
**Pull request by pranavanba**
Depends on #7 

## Major Changes

1. Create `config.yml` file to store pipeline parameters as `key: value` pairs in yml format
2. Get `config.yml` `key: value` pairs using `config::get(config = "prod")` and store output in global environment

## Minor Changes

1. Remove references to `params.R`

### CODE REVIEW

**Comment by itismeghasyam** [comment]
Other than the one issue raised above, this PR looks good to me

**Comment by pranavanba** [comment]
> Other than the one issue raised above, this PR looks good to me

What issue are you referring to @itismeghasyam?

**Comment by itismeghasyam** [comment]
@pranavanba, the one mentioned in the review. Let me copy paste here.

(for L#6 in config.yml)
I see in the current params.R file, the base key is 'main/parquet/' - an extra '/' in the end. Is it ok to not have it here? (asking as it might cause issues with paste0). Same comment for

PARQUET_BUCKET_BASE_KEY_EXTERNAL
PARQUET_BUCKET_BASE_KEY_ARCHIVE

**Comment by pranavanba** [comment]
> @pranavanba, the one mentioned in the review. Let me copy paste here.
> 
> (for L#6 in config.yml) I see in the current params.R file, the base key is 'main/parquet/' - an extra '/' in the end. Is it ok to not have it here? (asking as it might cause issues with paste0). Same comment for
> 
> PARQUET_BUCKET_BASE_KEY_EXTERNAL PARQUET_BUCKET_BASE_KEY_ARCHIVE

Thanks for pointing this out Megha. I've updated the config file.

**Pull request merged**
